// <auto-generated />
using System;
using EducationalWebGame.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EducationalWebGame.Migrations
{
    [DbContext(typeof(EducationalWebGameContext))]
    [Migration("20210106214825_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EducationalWebGame.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CoinsGiven");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("ExtraInfo")
                        .HasMaxLength(255);

                    b.Property<int?>("GameTypeId");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255);

                    b.Property<long>("PointsGiven");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Games");

                    b.HasData(
                        new { Id = 1, CoinsGiven = 30L, CorrectAnswer = "В О Д А", GameTypeId = 1, PointsGiven = 30L, Question = "Вещество, което разтваря някои вещества, а други не, не гори и не поддържа горенето.", SubjectId = 1 },
                        new { Id = 2, CoinsGiven = 10L, CorrectAnswer = "Д Ъ Р В О", GameTypeId = 1, PointsGiven = 10L, Question = "Вещество, което може да гори и се използва за отопление.", SubjectId = 1 },
                        new { Id = 3, CoinsGiven = 20L, CorrectAnswer = "М Е Т А Л И", GameTypeId = 1, PointsGiven = 20L, Question = "Как наричаме най-добрите проводници на топлина? От тях се изработват отоплителни уреди, домакински съдове и др.", SubjectId = 1 },
                        new { Id = 4, CoinsGiven = 30L, CorrectAnswer = "В Ъ Л Н А", GameTypeId = 1, PointsGiven = 30L, Question = "Вещество, което не пропуска топлината да премине през него. Използва се за изработването на дрехи. Носим ги през зимата.", SubjectId = 1 },
                        new { Id = 5, CoinsGiven = 20L, CorrectAnswer = "М А Г Н И Т", GameTypeId = 1, PointsGiven = 20L, Question = "Привлича предмети направени от желязо, стомана и някои други метали.", SubjectId = 1 },
                        new { Id = 6, CoinsGiven = 10L, CorrectAnswer = "Т О П К А", GameTypeId = 1, PointsGiven = 10L, Question = "Тяло, което е по-леко от водата. Можем да играем с него.", SubjectId = 1 },
                        new { Id = 7, CoinsGiven = 10L, CorrectAnswer = "М О Н Е Т А", GameTypeId = 1, PointsGiven = 10L, Question = "Тяло, което е по-тежко от водата. Можем да си купим нещо с него.", SubjectId = 1 },
                        new { Id = 8, CoinsGiven = 20L, CorrectAnswer = "Т Е Р М О М Е Т Ъ Р", GameTypeId = 1, PointsGiven = 20L, Question = "Специален уред за точното измерване на температурата.", SubjectId = 1 },
                        new { Id = 9, CoinsGiven = 30L, CorrectAnswer = "С И Н О П Т И Ц И", GameTypeId = 1, PointsGiven = 30L, Question = "Как се наричат хората, които изработват прогнозата за времето?", SubjectId = 1 },
                        new { Id = 10, CoinsGiven = 10L, CorrectAnswer = "В О Д А", GameTypeId = 1, PointsGiven = 10L, Question = "Вещество в природата, без което животът на организмите - хора, животни, растения е немислим.", SubjectId = 1 },
                        new { Id = 11, CoinsGiven = 20L, CorrectAnswer = "Л Е Д", GameTypeId = 1, PointsGiven = 20L, Question = "Водата се среща в три агрегатни състояния - твърдо, течно и газообразно. Как наричаме водата, когато е в твърдо състояние?", SubjectId = 1 },
                        new { Id = 12, CoinsGiven = 30L, CorrectAnswer = "Б У Р Я", GameTypeId = 1, PointsGiven = 30L, Question = "Какво наближава ако мравките бързат към мравуняците си?", SubjectId = 1 },
                        new { Id = 13, CoinsGiven = 10L, CorrectAnswer = "С Н Я Г", GameTypeId = 1, PointsGiven = 10L, Question = "Има различни видове валежи. Какво вали през зимата?", SubjectId = 1 },
                        new { Id = 14, CoinsGiven = 20L, CorrectAnswer = "Г Р А Д У Ш К А", GameTypeId = 1, PointsGiven = 20L, Question = "Как се нарича валежът, когато водните капки падат на земята като твърди ледени зърна?", SubjectId = 1 },
                        new { Id = 15, CoinsGiven = 30L, CorrectAnswer = "К Р Ъ Г О В Р А Т", GameTypeId = 1, PointsGiven = 30L, Question = "Как се нарича постоянното преминаване на водата от едно състояние в друго?", SubjectId = 1 },
                        new { Id = 16, CoinsGiven = 20L, CorrectAnswer = "П О Ч В А", GameTypeId = 1, PointsGiven = 20L, Question = "Как се нарича най-горният рохкав слой на земята?", SubjectId = 1 },
                        new { Id = 17, CoinsGiven = 30L, CorrectAnswer = "С Л У Х", GameTypeId = 1, PointsGiven = 30L, Question = "Как се нарича способността на ушите да чуват звуци?", SubjectId = 1 },
                        new { Id = 18, CoinsGiven = 10L, CorrectAnswer = "У Х О", GameTypeId = 1, PointsGiven = 10L, Question = "Сетивен орган, с който чуваме звуци.", SubjectId = 1 },
                        new { Id = 19, CoinsGiven = 30L, CorrectAnswer = "Г Л О Б У С", GameTypeId = 1, PointsGiven = 30L, Question = "Изображение на земното кълбо в умален вид.", SubjectId = 2 },
                        new { Id = 20, CoinsGiven = 20L, CorrectAnswer = "С Е Д Е М", GameTypeId = 1, PointsGiven = 20L, Question = "Колко са континентите на земята?", SubjectId = 2 },
                        new { Id = 21, CoinsGiven = 10L, CorrectAnswer = "Е В Р О П А", GameTypeId = 1, PointsGiven = 10L, Question = "В кой континент се намира България?", SubjectId = 2 },
                        new { Id = 22, CoinsGiven = 30L, CorrectAnswer = "О С Т Р О В", GameTypeId = 1, PointsGiven = 30L, Question = "Суша, заобградена от всички страни с вода.", SubjectId = 2 },
                        new { Id = 23, CoinsGiven = 20L, CorrectAnswer = "Р У Д И", GameTypeId = 1, PointsGiven = 20L, Question = "Скали, от които след преработка се получават метали.", SubjectId = 2 },
                        new { Id = 24, CoinsGiven = 10L, CorrectAnswer = "Д У Н А В", GameTypeId = 1, PointsGiven = 10L, Question = "Българска гранична река. Тя е границата между България и Румъния.", SubjectId = 2 },
                        new { Id = 25, CoinsGiven = 30L, CorrectAnswer = "Б Ъ Л Г А Р И Я", GameTypeId = 1, PointsGiven = 30L, Question = "Държава на Балканския полуостров, която е на четвърто място по големина.", SubjectId = 2 },
                        new { Id = 26, CoinsGiven = 20L, CorrectAnswer = "С Ъ Р Б И Я", GameTypeId = 1, PointsGiven = 20L, Question = "Държава, с която граничим на запад.", SubjectId = 2 },
                        new { Id = 27, CoinsGiven = 10L, CorrectAnswer = "И С К Ъ Р", GameTypeId = 1, PointsGiven = 10L, Question = "Коя е най-дългата българска река?", SubjectId = 2 },
                        new { Id = 28, CoinsGiven = 30L, CorrectAnswer = "Р Е З Е Р В А Т", GameTypeId = 1, PointsGiven = 30L, Question = "Защитено място, където се опазват редки растителни и животински видове.", SubjectId = 2 },
                        new { Id = 29, CoinsGiven = 20L, CorrectAnswer = "Г Ъ Р Ц И Я", GameTypeId = 1, PointsGiven = 20L, Question = "Държава, с която граничим на юг.", SubjectId = 2 },
                        new { Id = 30, CoinsGiven = 10L, CorrectAnswer = "С О Ф И Я", GameTypeId = 1, PointsGiven = 10L, Question = "Столицата на нашата държава.", SubjectId = 2 },
                        new { Id = 31, CoinsGiven = 30L, CorrectAnswer = "К О З Л О Д У Й", GameTypeId = 1, PointsGiven = 30L, Question = "Град в България. Там има атомна електроцентрала.", SubjectId = 2 },
                        new { Id = 32, CoinsGiven = 20L, CorrectAnswer = "Д О Б Р У Д Ж А", GameTypeId = 1, PointsGiven = 20L, Question = "Житницата на България.", SubjectId = 2 },
                        new { Id = 33, CoinsGiven = 10L, CorrectAnswer = "Р У С Е", GameTypeId = 1, PointsGiven = 10L, Question = "Голямо селище в Дунавската равнина. Намира се на река Дунав.", SubjectId = 2 },
                        new { Id = 34, CoinsGiven = 30L, CorrectAnswer = "С Р Е Б Ъ Р Н А", GameTypeId = 1, PointsGiven = 30L, Question = "Резерват, западно от град Силистра, езеро, свързано с река Дунав -  220 вида птици - пеликани, чапли, патици.", SubjectId = 2 },
                        new { Id = 35, CoinsGiven = 20L, CorrectAnswer = "Б О Т Е В", GameTypeId = 1, PointsGiven = 20L, Question = "Най-високият връх в Стара планина. Висок е 2376 м.", SubjectId = 2 },
                        new { Id = 36, CoinsGiven = 10L, CorrectAnswer = "Р И Л А", GameTypeId = 1, PointsGiven = 10L, Question = "Най- високият връх в България е Мусала - 2925 м. В коя планина се намира той?", SubjectId = 2 },
                        new { Id = 37, CoinsGiven = 20L, CorrectAnswer = "ХУМУС", ExtraInfo = "УХСМУ", GameTypeId = 2, PointsGiven = 20L, Question = "Съставка на почвата, която се образува от изгнили части на растения, измрели животни и други организми. Богата е на хранителни вещества.", SubjectId = 1 },
                        new { Id = 38, CoinsGiven = 10L, CorrectAnswer = "ПРАХ", ExtraInfo = "ГТСХАЕПОРБЛЯ", GameTypeId = 2, PointsGiven = 10L, Question = "Нещо, което замърсява въздуха.", SubjectId = 1 },
                        new { Id = 39, CoinsGiven = 30L, CorrectAnswer = "ШУМ", ExtraInfo = "УМШАВ", GameTypeId = 2, PointsGiven = 30L, Question = "Как наричаме смесването на различни звуци?", SubjectId = 1 },
                        new { Id = 40, CoinsGiven = 10L, CorrectAnswer = "ВЕРИГИ", ExtraInfo = "ИРВИЕГ", GameTypeId = 2, PointsGiven = 10L, Question = "Какво слагат на гумите на автомобила шофьорите през зимата, за да  се предпазят от подхлъзване?", SubjectId = 1 },
                        new { Id = 41, CoinsGiven = 20L, CorrectAnswer = "ГОРИВО", ExtraInfo = "ОРИГОВ", GameTypeId = 2, PointsGiven = 20L, Question = "Какво е необходимо на автобуса, за да се движи?", SubjectId = 1 },
                        new { Id = 42, CoinsGiven = 30L, CorrectAnswer = "ЕНЕРГИЯ", ExtraInfo = "ГИЯРЕНЕ", GameTypeId = 2, PointsGiven = 30L, Question = "Как наричаме способността на тялото да извършва работа?", SubjectId = 1 },
                        new { Id = 43, CoinsGiven = 30L, CorrectAnswer = "ЗВУК", ExtraInfo = "УВКЗ", GameTypeId = 2, PointsGiven = 30L, Question = "Как се наричат разпространените във въздуха трептения?", SubjectId = 1 },
                        new { Id = 44, CoinsGiven = 20L, CorrectAnswer = "ПЯСЪК", ExtraInfo = "КСПЯЪ", GameTypeId = 2, PointsGiven = 20L, Question = "Една от съставките на почвата, благодарение на която се задържа малко вода.", SubjectId = 1 },
                        new { Id = 45, CoinsGiven = 10L, CorrectAnswer = "НЕФТ", ExtraInfo = "ТФНЕ", GameTypeId = 2, PointsGiven = 10L, Question = "Един от замърсителите на водата.", SubjectId = 1 },
                        new { Id = 46, CoinsGiven = 10L, CorrectAnswer = "СЛЪНЦЕ", ExtraInfo = "ЕНЦСЪЛ", GameTypeId = 2, PointsGiven = 10L, Question = "Най-големият източник на светлина.", SubjectId = 1 },
                        new { Id = 47, CoinsGiven = 20L, CorrectAnswer = "ЛУНА", ExtraInfo = "УЛАН", GameTypeId = 2, PointsGiven = 20L, Question = "Кой е естественият спътник на Земята?", SubjectId = 1 },
                        new { Id = 48, CoinsGiven = 30L, CorrectAnswer = "ЗРЕНИЕ", ExtraInfo = "ЕРЕЗНИ", GameTypeId = 2, PointsGiven = 30L, Question = "Как се нарича способността на човека да вижда телата около себе си и да разпознава цветовете?", SubjectId = 1 },
                        new { Id = 49, CoinsGiven = 30L, CorrectAnswer = "ПЛАНЕТА", ExtraInfo = "АПТЛАНЕ", GameTypeId = 2, PointsGiven = 30L, Question = "Небесно тяло, което не излъчва собствена светлина и топлина, а свети с отразена слънчева светлина.", SubjectId = 1 },
                        new { Id = 50, CoinsGiven = 20L, CorrectAnswer = "ЗВЕЗДА", ExtraInfo = "АЗДВЗЕ", GameTypeId = 2, PointsGiven = 20L, Question = "Небесно тяло, което излъчва собствена светлина и топлина", SubjectId = 1 },
                        new { Id = 51, CoinsGiven = 10L, CorrectAnswer = "ЗЕМЯ", ExtraInfo = "МЕЯЗ", GameTypeId = 2, PointsGiven = 10L, Question = "Планета от Слънчевата система, на която има живот.", SubjectId = 1 },
                        new { Id = 52, CoinsGiven = 30L, CorrectAnswer = "МАРС", ExtraInfo = "СРАМ", GameTypeId = 2, PointsGiven = 30L, Question = "Четвъртата планета от Слънчевата система. Наричат я червената планета.", SubjectId = 1 },
                        new { Id = 53, CoinsGiven = 20L, CorrectAnswer = "ЮПИТЕР", ExtraInfo = "РПЮЕТИ", GameTypeId = 2, PointsGiven = 20L, Question = "Най-голямата планета в Слънчевата система.", SubjectId = 1 },
                        new { Id = 54, CoinsGiven = 10L, CorrectAnswer = "ИЗТОК", ExtraInfo = "ТОКЗИ", GameTypeId = 2, PointsGiven = 10L, Question = "От каква посока изгрява Слънцето сутрин?", SubjectId = 1 },
                        new { Id = 55, CoinsGiven = 10L, CorrectAnswer = "МАРИЦА", ExtraInfo = "АМЦАИР", GameTypeId = 2, PointsGiven = 10L, Question = "Река, извираща от Рила планина. Протича през град Пловдив.", SubjectId = 2 },
                        new { Id = 56, CoinsGiven = 20L, CorrectAnswer = "АРДА", ExtraInfo = "АДАР", GameTypeId = 2, PointsGiven = 20L, Question = "Голяма река в  Рило - Родопската област. Протича през град Кърджали.", SubjectId = 2 },
                        new { Id = 57, CoinsGiven = 30L, CorrectAnswer = "ВИХРЕН", ExtraInfo = "НВИЕРХ", GameTypeId = 2, PointsGiven = 30L, Question = "Кой е най-високият връх в Пирин планина? Висок е 2914 м.", SubjectId = 2 },
                        new { Id = 58, CoinsGiven = 10L, CorrectAnswer = "ДЕВИН", ExtraInfo = "НДВЕИ", GameTypeId = 2, PointsGiven = 10L, Question = "Град в Рило - Родопската област, известен с минералните си извори.", SubjectId = 2 },
                        new { Id = 59, CoinsGiven = 20L, CorrectAnswer = "ЯНТРА", ExtraInfo = "АТЯРН", GameTypeId = 2, PointsGiven = 20L, Question = "Река, извираща от Стара планина. Минава през град Габрово.", SubjectId = 2 },
                        new { Id = 60, CoinsGiven = 30L, CorrectAnswer = "КОТЕЛ", ExtraInfo = "ЛКОЕТ", GameTypeId = 2, PointsGiven = 30L, Question = "Град в България, известен с развитието на тъкачеството.", SubjectId = 2 },
                        new { Id = 61, CoinsGiven = 10L, CorrectAnswer = "ВАРНА", ExtraInfo = "АВНАР", GameTypeId = 2, PointsGiven = 10L, Question = "Голямо пристанище на Черноморското ни крайбрежие. Наричаме града \"морската столица\" на България.", SubjectId = 2 },
                        new { Id = 62, CoinsGiven = 20L, CorrectAnswer = "ВИТОША", ExtraInfo = "АВШИОТ", GameTypeId = 2, PointsGiven = 20L, Question = "В коя планина се намира Черни връх. Висок е 2290 м.", SubjectId = 2 },
                        new { Id = 63, CoinsGiven = 30L, CorrectAnswer = "БОГДАН", ExtraInfo = "НБОАГД", GameTypeId = 2, PointsGiven = 30L, Question = "Най-високият връх в Средна гора.", SubjectId = 2 },
                        new { Id = 64, CoinsGiven = 20L, CorrectAnswer = "СИНАГОГА", ExtraInfo = "АСИГНОАГ", GameTypeId = 2, PointsGiven = 20L, Question = "Еврейски молитвен дом.", SubjectId = 2 },
                        new { Id = 65, CoinsGiven = 10L, CorrectAnswer = "ДЕЛФИН", ExtraInfo = "НДЕИЛФ", GameTypeId = 2, PointsGiven = 10L, Question = "Морски обитател във водите на Черно море. Много красив морски бозайник.", SubjectId = 2 },
                        new { Id = 66, CoinsGiven = 30L, CorrectAnswer = "МУФЛОН", ExtraInfo = "НМУОЛФ", GameTypeId = 2, PointsGiven = 30L, Question = "Застрашено от изчезване животно, вписано в Червената книга на България.", SubjectId = 2 },
                        new { Id = 67, CoinsGiven = 10L, CorrectAnswer = "БУРГАС", ExtraInfo = "СБУАГР", GameTypeId = 2, PointsGiven = 10L, Question = "Град на Черноморското ни крайбрежие, където се добива морска сол.", SubjectId = 2 },
                        new { Id = 68, CoinsGiven = 20L, CorrectAnswer = "МУРА", ExtraInfo = "УРАМ", GameTypeId = 2, PointsGiven = 20L, Question = "Вид иглолистно дърво .", SubjectId = 2 },
                        new { Id = 69, CoinsGiven = 30L, CorrectAnswer = "ПЛОВДИВ", ExtraInfo = "ВПЛДВОИ", GameTypeId = 2, PointsGiven = 30L, Question = "В кой български град на 6 септември 1885 година било провъзгласено Съединението на България?", SubjectId = 2 },
                        new { Id = 70, CoinsGiven = 10L, CorrectAnswer = "ЧАЙКА", ExtraInfo = "АКЧЙА", GameTypeId = 2, PointsGiven = 10L, Question = "Птица, живееща по бреговете, реките и езерата на Черноморското ни крайбрежие.", SubjectId = 2 },
                        new { Id = 71, CoinsGiven = 20L, CorrectAnswer = "ТРОЯН", ExtraInfo = "НТРЯО", GameTypeId = 2, PointsGiven = 20L, Question = "Град в България, известен с развитието на занаятите, основно грънчарство .", SubjectId = 2 },
                        new { Id = 72, CoinsGiven = 30L, CorrectAnswer = "ЛЕДЕНИКА", ExtraInfo = "АЛЕКИДНЕ", GameTypeId = 2, PointsGiven = 30L, Question = "Пещера в Стара планина.", SubjectId = 2 },
                        new { Id = 73, CoinsGiven = 10L, CorrectAnswer = "Почвата съдържа различни вещества.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 74, CoinsGiven = 20L, CorrectAnswer = "Плодородната почва съдържа повече хумус.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 75, CoinsGiven = 30L, CorrectAnswer = "Шумът е вреден за човешкото здраве.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 76, CoinsGiven = 10L, CorrectAnswer = "Пазете природата чиста!", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 77, CoinsGiven = 20L, CorrectAnswer = "Земята има формата на кълбо.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 78, CoinsGiven = 30L, CorrectAnswer = "Слънцето е най-големият източник на светлина.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 79, CoinsGiven = 10L, CorrectAnswer = "Юпитер е най-голямата планета.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 80, CoinsGiven = 20L, CorrectAnswer = "Луната обикаля около Земята.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 81, CoinsGiven = 30L, CorrectAnswer = "Около Слънцето обикалят осем планети.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 82, CoinsGiven = 10L, CorrectAnswer = "Глиганът е всеядно животно.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 83, CoinsGiven = 20L, CorrectAnswer = "Спазвай добра лична хигиена!", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 84, CoinsGiven = 30L, CorrectAnswer = "Земята обикаля около Слънцето.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 85, CoinsGiven = 10L, CorrectAnswer = "Орелът има отлично зрение.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 86, CoinsGiven = 20L, CorrectAnswer = "Прилепите са летящи бозайници.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 87, CoinsGiven = 30L, CorrectAnswer = "Яйцата на рибите се наричат хайвер.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 88, CoinsGiven = 10L, CorrectAnswer = "Жабата е земноводно животно.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 89, CoinsGiven = 20L, CorrectAnswer = "Алкохолът уврежда човешкия организъм.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 90, CoinsGiven = 30L, CorrectAnswer = "Спазвайте добра лична хигиена!", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 1 },
                        new { Id = 91, CoinsGiven = 10L, CorrectAnswer = "Искър е най-дългата българска река.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 92, CoinsGiven = 20L, CorrectAnswer = "Добруджа е житницата на България.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 93, CoinsGiven = 30L, CorrectAnswer = "Град Добрич се намира в Дунавската равнина.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 94, CoinsGiven = 10L, CorrectAnswer = "Мурата е иглолистно дърво.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 95, CoinsGiven = 20L, CorrectAnswer = "София е столица на България.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 96, CoinsGiven = 30L, CorrectAnswer = "България се намира в Европа.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 97, CoinsGiven = 10L, CorrectAnswer = "Сребърна е резерват.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 98, CoinsGiven = 20L, CorrectAnswer = "Мусала е най-високият връх в България.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 99, CoinsGiven = 30L, CorrectAnswer = "На запад граничим със Сърбия.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 100, CoinsGiven = 10L, CorrectAnswer = "Българите превземат Одрин.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 101, CoinsGiven = 20L, CorrectAnswer = "В Поморие се добива морска сол.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 102, CoinsGiven = 30L, CorrectAnswer = "Конституцията е основният закон на държавата.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 103, CoinsGiven = 10L, CorrectAnswer = "Пловдив е разположен на река Марица.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 104, CoinsGiven = 20L, CorrectAnswer = "Девин е известен с минералните си извори.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 105, CoinsGiven = 30L, CorrectAnswer = "Континентите на Земята са седем.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 106, CoinsGiven = 10L, CorrectAnswer = "Варна е морската столица на България.", GameTypeId = 3, PointsGiven = 10L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 107, CoinsGiven = 20L, CorrectAnswer = "На юг граничим с Гърция.", GameTypeId = 3, PointsGiven = 20L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 108, CoinsGiven = 30L, CorrectAnswer = "Муфлонът е застрашено от изчезване животно.", GameTypeId = 3, PointsGiven = 30L, Question = "Подредете думите в изречение!", SubjectId = 2 },
                        new { Id = 109, CoinsGiven = 10L, CorrectAnswer = "Юпитер", ExtraInfo = "Сатурн  Юпитер  Земя", GameTypeId = 4, ImagePath = "vapros1.jpeg", PointsGiven = 10L, Question = "Коя планета е посочена на снимката? Това е най-голямата планета в Слънчевата Система.", SubjectId = 1 },
                        new { Id = 110, CoinsGiven = 20L, CorrectAnswer = "Сатурн", ExtraInfo = "Венера  Юпитер  Сатурн", GameTypeId = 4, ImagePath = "vapros2.jpg", PointsGiven = 20L, Question = "Името на планета от Слънчевата система.", SubjectId = 1 },
                        new { Id = 111, CoinsGiven = 30L, CorrectAnswer = "къртица", ExtraInfo = "попово прасе  лалугер  къртица", GameTypeId = 4, ImagePath = "vapros3.jpg", PointsGiven = 30L, Question = "Кое е изобразеното на снимката животно?", SubjectId = 1 },
                        new { Id = 112, CoinsGiven = 10L, CorrectAnswer = "черен щъркел", ExtraInfo = "бял щъркел  пъстър щъркер  черен щъркел", GameTypeId = 4, ImagePath = "vapros4.jpg", PointsGiven = 10L, Question = "Кое е това животно?  Вписано е в Червената книга на България?", SubjectId = 1 },
                        new { Id = 113, CoinsGiven = 30L, CorrectAnswer = "белогърб кълвач", ExtraInfo = "пъстър кълвач  дребен кълвач  белогърб кълвач", GameTypeId = 4, ImagePath = "vapros5.jpg", PointsGiven = 30L, Question = "Кое е това животно?  Вписано е в Червената книга на България?", SubjectId = 1 },
                        new { Id = 114, CoinsGiven = 20L, CorrectAnswer = "черен кълвач", ExtraInfo = "белезникав кълвач  черен кълвач  шарен кълвач", GameTypeId = 4, ImagePath = "vapros6.jpg", PointsGiven = 20L, Question = "Кое е това животно?  Вписано е в Червената книга на България?", SubjectId = 1 },
                        new { Id = 115, CoinsGiven = 30L, CorrectAnswer = "малък креслив орел", ExtraInfo = "сокол орко  малък креслив орел  голям ястреб", GameTypeId = 4, ImagePath = "vapros7.jpg", PointsGiven = 30L, Question = "Кое е това животно?  Вписано е в Червената книга на България?", SubjectId = 1 },
                        new { Id = 116, CoinsGiven = 20L, CorrectAnswer = "скален орел", ExtraInfo = "орел змияр  сокол орко  скален орел", GameTypeId = 4, ImagePath = "vapros8.jpg", PointsGiven = 20L, Question = "Кое е това животно?  Вписано е в Червената книга на България?", SubjectId = 1 },
                        new { Id = 117, CoinsGiven = 10L, CorrectAnswer = "орел змияр", ExtraInfo = "скален орел  орел змияр  малък креслив орел", GameTypeId = 4, ImagePath = "vapros9.jpg", PointsGiven = 10L, Question = "Кое е това животно?  Вписано е в Червената книга на България?", SubjectId = 1 },
                        new { Id = 118, CoinsGiven = 30L, CorrectAnswer = "голям ястреб", ExtraInfo = "голям ястреб  сокол орко  ловен сокол", GameTypeId = 4, ImagePath = "vapros10.jpg", PointsGiven = 30L, Question = "Кое е това животно?  Вписано е в Червената книга на България?", SubjectId = 1 },
                        new { Id = 119, CoinsGiven = 20L, CorrectAnswer = "брадат лешояд", ExtraInfo = "черен лешояд  брадат лешояд  бекасина", GameTypeId = 4, ImagePath = "vapros11.jpeg", PointsGiven = 20L, Question = "Кое е това животно - изчезнал вид?  Вписано е в Червената книга на България?", SubjectId = 1 },
                        new { Id = 120, CoinsGiven = 10L, CorrectAnswer = "розов пеликан", ExtraInfo = "червен ангъч  сив жерав  розов пеликан", GameTypeId = 4, ImagePath = "vapros12.jpg", PointsGiven = 10L, Question = "Кое е това животно - изчезнал вид?  Вписано е в Червената книга на България?", SubjectId = 1 },
                        new { Id = 121, CoinsGiven = 10L, CorrectAnswer = "ветрогенератор", ExtraInfo = "вятърна мелница  ветрогенератор  въртележка", GameTypeId = 4, ImagePath = "vapros13.jpg", PointsGiven = 10L, Question = "Какво виждате на изображението?", SubjectId = 1 },
                        new { Id = 122, CoinsGiven = 20L, CorrectAnswer = "слънчеви панели", ExtraInfo = "ветрогенератор  оранжерия  слънчеви панели", GameTypeId = 4, ImagePath = "vapros14.jpg", PointsGiven = 20L, Question = "Какво виждате на изображението?", SubjectId = 1 },
                        new { Id = 123, CoinsGiven = 30L, CorrectAnswer = "лалугер", ExtraInfo = "попово прасе  сляпо куче  лалугер", GameTypeId = 4, ImagePath = "vapros15.jpg", PointsGiven = 30L, Question = "Кое е това животно?", SubjectId = 1 },
                        new { Id = 124, CoinsGiven = 10L, CorrectAnswer = "сива чапла", ExtraInfo = "голяма бяла чапла  чайка  сива чапла", GameTypeId = 4, ImagePath = "vapros16.jpg", PointsGiven = 10L, Question = "Кое е това животно?", SubjectId = 1 },
                        new { Id = 125, CoinsGiven = 20L, CorrectAnswer = "голяма бяла чапла", ExtraInfo = "голяма бяла чапла  чайка  сива чапла", GameTypeId = 4, ImagePath = "vapros17.jpg", PointsGiven = 20L, Question = "Кое е това животно?", SubjectId = 1 },
                        new { Id = 126, CoinsGiven = 30L, CorrectAnswer = "златка", ExtraInfo = "дива котка  златка  пъстър пор", GameTypeId = 4, ImagePath = "vapros18.jpg", PointsGiven = 30L, Question = "Кое е това животно?", SubjectId = 1 },
                        new { Id = 127, CoinsGiven = 10L, CorrectAnswer = "Васил Левски", ExtraInfo = "Васил Левски  Христо Ботев  Иван Вазов", GameTypeId = 4, ImagePath = "vapros19.jpeg", PointsGiven = 10L, Question = "Кой велик българин е изобразен на долната картинка?", SubjectId = 2 },
                        new { Id = 128, CoinsGiven = 20L, CorrectAnswer = "Христо Ботев", ExtraInfo = "Васил Левски  Христо Ботев  Георги Раковски", GameTypeId = 4, ImagePath = "vapros20.jpg", PointsGiven = 20L, Question = "Това е един от водачите на българите, в борбата им за свобода", SubjectId = 2 },
                        new { Id = 129, CoinsGiven = 30L, CorrectAnswer = "Георги Раковски", ExtraInfo = "Христо Ботев  Васил Левски  Георги Раковски", GameTypeId = 4, ImagePath = "vapros21.jpg", PointsGiven = 30L, Question = "Това е един от водачите на българите, в борбата им за свобода", SubjectId = 2 },
                        new { Id = 130, CoinsGiven = 20L, CorrectAnswer = "Георги Бенковски", ExtraInfo = "Георги Раковски  Георги Бенковски  Христо Ботев", GameTypeId = 4, ImagePath = "vapros22.jpeg", PointsGiven = 20L, Question = "Това е един от водачите на българите, в борбата им за свобода - предводител на Хвърковатата чета по време на Априлското въстание.", SubjectId = 2 },
                        new { Id = 131, CoinsGiven = 10L, CorrectAnswer = "Герб на Република България", ExtraInfo = "Герб на Княжество България  Герб на Република България  Герб на град София", GameTypeId = 4, ImagePath = "vapros23.jpg", PointsGiven = 10L, Question = "Познайте кой е изобразеният на илюстрацията герб?", SubjectId = 2 },
                        new { Id = 132, CoinsGiven = 30L, CorrectAnswer = "Герб на Княжество България", ExtraInfo = "Герб на Княжество България  Герб на Република България  Герб на град София", GameTypeId = 4, ImagePath = "vapros24.png", PointsGiven = 30L, Question = "Познайте кой е изобразеният на илюстрацията герб?", SubjectId = 2 },
                        new { Id = 133, CoinsGiven = 20L, CorrectAnswer = "Герб на град София", ExtraInfo = "Герб на Княжество България  Герб на Република България  Герб на град София", GameTypeId = 4, ImagePath = "vapros25.png", PointsGiven = 20L, Question = "Познайте кой е изобразеният на илюстрацията герб?", SubjectId = 2 },
                        new { Id = 134, CoinsGiven = 10L, CorrectAnswer = "Сграда на Президенството", ExtraInfo = "Сграда на Президенството  Сграда на Народното събрание  Сграда на Министерски съвет", GameTypeId = 4, ImagePath = "vapros26.jpg", PointsGiven = 10L, Question = "Коя е сградата изобразена на илюстрацията?", SubjectId = 2 },
                        new { Id = 135, CoinsGiven = 30L, CorrectAnswer = "Паисий Хилендарски", ExtraInfo = "Софроний Врачански  Петър Берон  Паисий Хилендарски", GameTypeId = 4, ImagePath = "vapros27.jpg", PointsGiven = 30L, Question = "Кой е този български възрожденец?", SubjectId = 2 },
                        new { Id = 136, CoinsGiven = 10L, CorrectAnswer = "Румъния", ExtraInfo = "Сърбия  Турция  Румъния", GameTypeId = 4, ImagePath = "vapros28.jpg", PointsGiven = 10L, Question = "С коя държава граничим на север?", SubjectId = 2 },
                        new { Id = 137, CoinsGiven = 20L, CorrectAnswer = "Министерски съвет", ExtraInfo = "Министерски съвет  Народно събрание  Президенство", GameTypeId = 4, ImagePath = "vapros29.jpg", PointsGiven = 20L, Question = "Името на сградата, която виждате.", SubjectId = 2 },
                        new { Id = 138, CoinsGiven = 30L, CorrectAnswer = "Стефан Стамболов", ExtraInfo = "Петко Каравелов  Стефан Стамболов  Константин Стоилов", GameTypeId = 4, ImagePath = "vapros30.jpg", PointsGiven = 30L, Question = "Това е един от най-изявените политици на България след Освобождението от турско робство. Бил е председател на Народното събрание, последовател на Васил Левски и апостол по време на Априлското въстание.", SubjectId = 2 },
                        new { Id = 139, CoinsGiven = 10L, CorrectAnswer = "Народно събрание", ExtraInfo = "Министерски съвет  Народно събрание  Президенство", GameTypeId = 4, ImagePath = "vapros31.jpg", PointsGiven = 10L, Question = "Името на сградата, която виждате", SubjectId = 2 },
                        new { Id = 140, CoinsGiven = 20L, CorrectAnswer = "Богоявление", ExtraInfo = "Васильовден  Ивановден  Богоявление", GameTypeId = 4, ImagePath = "vapros32.jpg", PointsGiven = 20L, Question = "На кой празник мъжете от Калофер играят в ледените води на река Тунджа хоро, признато за единствена традиция в света?", SubjectId = 2 },
                        new { Id = 141, CoinsGiven = 30L, CorrectAnswer = "Райското пръскало", ExtraInfo = "Водно огледало  Райското пръскало  Течащите скали", GameTypeId = 4, ImagePath = "vapros33.jpg", PointsGiven = 30L, Question = "Това е най-високият водопад у нас.Как се нарича?", SubjectId = 2 },
                        new { Id = 142, CoinsGiven = 10L, CorrectAnswer = "Боят на връх Шипка", ExtraInfo = "Боят на връх Шипка  Атаката на Одрин  Боят при Чаталджа", GameTypeId = 4, ImagePath = "vapros34.jpg", PointsGiven = 10L, Question = "Художникът Димитър Гюдженов е пресъздал епизод от славната българска история. Как се нарича тази картина?", SubjectId = 2 },
                        new { Id = 143, CoinsGiven = 30L, CorrectAnswer = "паметник на Съединението в град Пловдив", ExtraInfo = "паметник на Съединението в град Пловдив  паметник на Асеневци във Велико Търново  паметник на цар Самуил", GameTypeId = 4, ImagePath = "vapros35.png", PointsGiven = 30L, Question = "Кой е този паметник?", SubjectId = 2 },
                        new { Id = 144, CoinsGiven = 20L, CorrectAnswer = "Царевец", ExtraInfo = "Самуилова крепост  Царевец  Мадарска крепост", GameTypeId = 4, ImagePath = "vapros36.jpg", PointsGiven = 20L, Question = "Коя е тази крепост?", SubjectId = 2 },
                        new { Id = 145, CoinsGiven = 10L, CorrectAnswer = "КОН", ExtraInfo = "1. 11-та буква от азбуката. 2. 15-та буква от азбуката. 3. 14-та буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Разгадайте шифъра! Това е тревопасно животно, което може да се язди", SubjectId = 1 },
                        new { Id = 146, CoinsGiven = 20L, CorrectAnswer = "ОРЕЛ", ExtraInfo = "1. 15-та буква от азбуката. 2. 17-та буква от азбуката. 3. 6-та буква от азбуката. 4. 12-та буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Разгадайте шифъра! Хищна птица - има отлично зрение, силни мускули, здрави нокти и остра извита човка", SubjectId = 1 },
                        new { Id = 147, CoinsGiven = 30L, CorrectAnswer = "СОВА", ExtraInfo = "1. 18-та буква от азбуката. 2. 15-та буква от азбуката. 3. 3-та буква от азбуката. 4. 1-ва буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Разгадайте шифъра! Нощна граблива птица", SubjectId = 1 },
                        new { Id = 148, CoinsGiven = 10L, CorrectAnswer = "ЛЪВ", ExtraInfo = "1. 12-та буква от азбуката. 2. 27-ма буква от азбуката. 3. 3-та буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Разгадайте шифъра! Хищен бозайник. Това е царят на животните.", SubjectId = 1 },
                        new { Id = 149, CoinsGiven = 20L, CorrectAnswer = "ЕЛЕН", ExtraInfo = "1. 6-та буква от азбуката. 2. 12-та буква от азбуката. 3. 6-та буква от азбуката. 4. 14-та буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Отгатнете шифъра!  Красиво тревопасно горско животно с големи рога.", SubjectId = 1 },
                        new { Id = 150, CoinsGiven = 30L, CorrectAnswer = "ЖАБА", ExtraInfo = "1. 7-ма буква от азбуката. 2. 1-ва буква от азбуката. 3. 2-ра буква от азбуката. 4. 1-ва буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Разгадайте шифъра! Животно с дълъг лепкав език, с който улавя различни насекоми. Живее във водата и на сушата.", SubjectId = 1 },
                        new { Id = 151, CoinsGiven = 10L, CorrectAnswer = "КИТ", ExtraInfo = "1. 11-та буква от азбуката. 2. 9-та буква от азбуката. 3. 19-та буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Отгатнете шифъра!  Най-големият морски бозайник.", SubjectId = 1 },
                        new { Id = 152, CoinsGiven = 20L, CorrectAnswer = "ДЪБ", ExtraInfo = "1. 5-та буква от азбуката. 2. 27-ма буква от азбуката. 3. 2-ра буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Разгадайте шифъра! Широколистно дърво, растящо в ниските планински места. Ражда жълъди, които са храна за дивите прасета.", SubjectId = 1 },
                        new { Id = 153, CoinsGiven = 30L, CorrectAnswer = "БРЕЗА", ExtraInfo = "1. 2-ра буква от азбуката. 2. 17-та буква от азбуката. 3. 6-та буква от азбуката. 4. 8-ма буква от азбуката. 5. 1-ва буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Отгатнете шифъра! Високо широколистно дърво с бяло стъбло.", SubjectId = 1 },
                        new { Id = 154, CoinsGiven = 10L, CorrectAnswer = "ШАРАН", ExtraInfo = "1. 25-та буква от азбуката. 2. 1-ва буква от азбуката. 3. 17-та буква от азбуката. 4. 1-ва буква от азбуката. 5. 14-та буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Разгадайте шифъра! Това е речна риба, която приготвяме за Никулден.", SubjectId = 1 },
                        new { Id = 155, CoinsGiven = 20L, CorrectAnswer = "СЪРЦЕ", ExtraInfo = "1. 18-та буква от азбуката. 2. 27-ма буква от азбуката. 3. 17-та буква от азбуката. 4. 23-та буква от азбуката. 5. 6-та буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Разгадайте шифъра! Кой е този важен човешки орган? Непрекъснато се свива и разпуска и движи кръвта в нашето тяло.", SubjectId = 1 },
                        new { Id = 156, CoinsGiven = 30L, CorrectAnswer = "ЛАЛЕ", ExtraInfo = "1. 12-та буква от азбуката. 2. 1-ва буква от азбуката. 3. 12-та буква от азбуката. 4. 6-та буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Отгатнете шифъра! Пролетно цвете с различни цветове, което се размножава чрез луковици.", SubjectId = 1 },
                        new { Id = 157, CoinsGiven = 10L, CorrectAnswer = "СЛОН", ExtraInfo = "1. 18-та буква от азбуката. 2. 12-та буква от азбуката. 3. 15-та буква от азбуката. 4. 14-та буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Разгадайте шифъра! Най-големият сухоземен бозайник . Има хобот.", SubjectId = 1 },
                        new { Id = 158, CoinsGiven = 20L, CorrectAnswer = "ХРИЛЕ", ExtraInfo = "1. 22-ра буква от азбуката. 2. 17-та буква от азбуката. 3. 9-та буква от азбуката. 4. 12-та буква от азбуката. 5. 6-та буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Разгадайте шифъра! С какво дишат рибите?", SubjectId = 1 },
                        new { Id = 159, CoinsGiven = 30L, CorrectAnswer = "МАРС", ExtraInfo = "1. 13-та буква от азбуката. 2. 1-ва буква от азбуката. 3. 17-та буква от азбуката. 4. 18-та буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Разгадайте шифъра! Четвъртата планета от Слънчевата система. Наричат я червената планета.", SubjectId = 1 },
                        new { Id = 160, CoinsGiven = 10L, CorrectAnswer = "НОС", ExtraInfo = "1. 14-та буква от азбуката. 2. 15-та буква от азбуката. 3. 18-та буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Разгадайте шифъра! Това е орган на дишането. С него долавяме различни миризми.", SubjectId = 1 },
                        new { Id = 161, CoinsGiven = 20L, CorrectAnswer = "БЯС", ExtraInfo = "1. 2-ра буква от азбуката. 2. 30-та буква от азбуката. 3. 18-та буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Отгатнете шифъра! Това е болест, която се причинява при ухапване от куче.", SubjectId = 1 },
                        new { Id = 162, CoinsGiven = 30L, CorrectAnswer = "ПЧЕЛА", ExtraInfo = "1. 16-та буква от азбуката. 2. 24-та буква от азбуката. 3. 6-та буква от азбуката. 4. 12-та буква от азбуката. 5. 1-ва буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Отгатнете шифъра! Това е животно, което няма бели дробове и диша чрез тънки разклонени тръбички / трахеи /.", SubjectId = 1 },
                        new { Id = 163, CoinsGiven = 10L, CorrectAnswer = "ГЕРБ", ExtraInfo = "1. 4-та буква от азбуката. 2. 6-та буква от азбуката. 3. 17-та буква от азбуката. 4. 2-ра буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Отгатнете шифъра! Това е един от държавните символи на България.", SubjectId = 2 },
                        new { Id = 164, CoinsGiven = 20L, CorrectAnswer = "КМЕТ", ExtraInfo = "1. 11-та буква от азбуката. 2. 13-та буква от азбуката. 3. 6-та буква от азбуката. 4. 19-та буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Отгатнете шифъра! Това е избран от гражданите представител, който управлява община, град или село.", SubjectId = 2 },
                        new { Id = 165, CoinsGiven = 30L, CorrectAnswer = "РУДИ", ExtraInfo = "1. 17-та буква от азбуката. 2. 20-та буква от азбуката. 3. 5-та буква от азбуката. 4. 9-та буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Отгатнете шифъра! Скали, от които след преработка се получават метали. Как се наричат те?", SubjectId = 2 },
                        new { Id = 166, CoinsGiven = 10L, CorrectAnswer = "ЗНАМЕ", ExtraInfo = "1. 8-ма буква от азбуката. 2. 14-та буква от азбуката. 3. 1-ва буква от азбуката. 4. 13-та буква от азбуката. 5. 6-та буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Разгадайте шифъра! Това е един от държавните символи на Република България", SubjectId = 2 },
                        new { Id = 167, CoinsGiven = 20L, CorrectAnswer = "ТОР", ExtraInfo = "1. 19-та буква от азбуката. 2. 15-та буква от азбуката. 3. 17-та буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Разгадайте шифъра! Вещество, използвано, за да се увеличат изкуствено плодородието на почвите.", SubjectId = 2 },
                        new { Id = 168, CoinsGiven = 30L, CorrectAnswer = "РИС", ExtraInfo = "1. 17-та буква от азбуката. 2. 9-та буква от азбуката. 3. 18-та буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Разгадайте шифъра! Това е защитено от изчезване животно, вписано в Червената книга на България.", SubjectId = 2 },
                        new { Id = 169, CoinsGiven = 10L, CorrectAnswer = "ХИМН", ExtraInfo = "1. 22-ра буква от азбуката. 2. 9-та буква от азбуката. 3. 13-та буква от азбуката. 4. 14-та буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Разгадайте шифъра! Един от държавните символи на България", SubjectId = 2 },
                        new { Id = 170, CoinsGiven = 20L, CorrectAnswer = "АРДА", ExtraInfo = "1. 1-ва буква от азбуката. 2. 17-та буква от азбуката. 3. 5-та буква от азбуката. 4. 1-ва буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Разгадайте шифъра! Голяма река, протичаща през Рило - Родопската област.", SubjectId = 2 },
                        new { Id = 171, CoinsGiven = 30L, CorrectAnswer = "БОРИС", ExtraInfo = "1. 2-ра буква от азбуката. 2. 15-та буква от азбуката. 3. 17-та буква от азбуката. 4. 9-та буква от азбуката. 5. 18-та буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Разгадайте шифъра! Това е името на български цар, наследил Фердинанд след войните за обединение и управлявал от 1918 до 1943 година.", SubjectId = 2 },
                        new { Id = 172, CoinsGiven = 10L, CorrectAnswer = "СОФИЯ", ExtraInfo = "1. 18-та буква от азбуката. 2. 15-та буква от азбуката. 3. 21-ва буква от азбуката. 4. 9-та буква от азбуката. 5. 30-та буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Разгадайте шифъра!Преходната област е най-населената част от България. Там се намира и нашата столица. Коя е тя?", SubjectId = 2 },
                        new { Id = 173, CoinsGiven = 20L, CorrectAnswer = "ТРОЯН", ExtraInfo = "1. 19-та буква от азбуката. 2. 17-та буква от азбуката. 3. 15-та буква от азбуката. 4. 30-та буква от азбуката. 5. 14-та буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Разгадайте шифъра! Кой е този град в България, известен с развитието на занаятите, основно грънчарство?", SubjectId = 2 },
                        new { Id = 174, CoinsGiven = 30L, CorrectAnswer = "ВИТ", ExtraInfo = "1. 3-та буква от азбуката. 2. 9-та буква от азбуката. 3. 19-та буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Разгадайте шифъра! Името на река, извираща от Стара планина.", SubjectId = 2 },
                        new { Id = 175, CoinsGiven = 20L, CorrectAnswer = "ИСКЪР", ExtraInfo = "1. 9-та буква от азбуката. 2. 18-та буква от азбуката. 3. 11-та буква от азбуката. 4. 27-ма буква от азбуката. 5. 17-та буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Разгадайте шифъра! Името на река, извираща от Рила планина.", SubjectId = 2 },
                        new { Id = 176, CoinsGiven = 10L, CorrectAnswer = "ДУНАВ", ExtraInfo = "1. 5-та буква от азбуката. 2. 20-та буква от азбуката. 3. 14-та буква от азбуката. 4. 1-ва буква от азбуката. 5. 3-та буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Разгадайте шифъра! Името на българска гранична река. Тя е границата между България и Румъния. ", SubjectId = 2 },
                        new { Id = 177, CoinsGiven = 30L, CorrectAnswer = "БОТЕВ", ExtraInfo = "1. 2-ра буква от азбуката. 2. 15-та буква от азбуката. 3. 19-та буква от азбуката. 4. 6-та буква от азбуката. 5. 3-та буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Разгадайте шифъра! Името на най-високия връх в Стара планина.", SubjectId = 2 },
                        new { Id = 178, CoinsGiven = 10L, CorrectAnswer = "РИЛА", ExtraInfo = "1. 17-та буква от азбуката. 2. 9-та буква от азбуката. 3. 12-та буква от азбуката. 4. 1-ва буква от азбуката.", GameTypeId = 5, PointsGiven = 10L, Question = "Разгадайте шифъра! Името на най-високата планина в България.", SubjectId = 2 },
                        new { Id = 179, CoinsGiven = 20L, CorrectAnswer = "РУСЕ", ExtraInfo = "1. 17-та буква от азбуката. 2. 20-та буква от азбуката. 3. 18-та буква от азбуката. 4. 6-та буква от азбуката.", GameTypeId = 5, PointsGiven = 20L, Question = "Разгадайте шифъра! Името на голям български град в Дунавската равнина. Намира се на река Дунав.", SubjectId = 2 },
                        new { Id = 180, CoinsGiven = 30L, CorrectAnswer = "ГУЩЕР", ExtraInfo = "1. 4-та буква от азбуката. 2. 20-та буква от азбуката. 3. 26-та буква от азбуката. 4. 6-та буква от азбуката. 5. 17-та буква от азбуката.", GameTypeId = 5, PointsGiven = 30L, Question = "Разгадайте шифъра! Животно с дълъг лепкав език, с който улавя различни насекоми.", SubjectId = 2 }
                    );
                });

            modelBuilder.Entity("EducationalWebGame.Models.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GameTypeName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("GameTypes");

                    b.HasData(
                        new { Id = 1, GameTypeName = "Бесеница" },
                        new { Id = 2, GameTypeName = "Подреди думата" },
                        new { Id = 3, GameTypeName = "Балони" },
                        new { Id = 4, GameTypeName = "Викторина" },
                        new { Id = 5, GameTypeName = "Шифър" }
                    );
                });

            modelBuilder.Entity("EducationalWebGame.Models.ResourceTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("ResourceTeachers");
                });

            modelBuilder.Entity("EducationalWebGame.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Coins");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<long>("Lives");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("Points");

                    b.Property<int?>("ResourceTeacherId");

                    b.Property<int?>("TeacherId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("ResourceTeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EducationalWebGame.Models.StudentGame", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<int>("GameId");

                    b.Property<bool>("IsCorrect");

                    b.HasKey("StudentId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("StudentGames");
                });

            modelBuilder.Entity("EducationalWebGame.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new { Id = 1, SubjectName = "Човекът и природата" },
                        new { Id = 2, SubjectName = "Човекът и обществото" }
                    );
                });

            modelBuilder.Entity("EducationalWebGame.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("EducationalWebGame.Models.Game", b =>
                {
                    b.HasOne("EducationalWebGame.Models.GameType", "GameType")
                        .WithMany("Games")
                        .HasForeignKey("GameTypeId");

                    b.HasOne("EducationalWebGame.Models.Subject", "Subject")
                        .WithMany("Games")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("EducationalWebGame.Models.Student", b =>
                {
                    b.HasOne("EducationalWebGame.Models.ResourceTeacher", "ResourceTeacher")
                        .WithMany("Students")
                        .HasForeignKey("ResourceTeacherId");

                    b.HasOne("EducationalWebGame.Models.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("EducationalWebGame.Models.StudentGame", b =>
                {
                    b.HasOne("EducationalWebGame.Models.Game", "Game")
                        .WithMany("StudentGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EducationalWebGame.Models.Student", "Student")
                        .WithMany("StudentGames")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
